/// Keyword index for the built-in emoji set, enabling the picker's search.
///
/// Only a curated subset of high-frequency emoji carry keywords (hand-written
/// to keep the payload small); unmapped emoji simply won't match a search.
/// Both Chinese and English keywords are indexed.
const Map<String, List<String>> kEmojiKeywords = {
  // 常用 / 笑脸
  '👍': ['赞', '好', 'thumbs', 'up', 'like', 'good'],
  '❤️': ['心', '爱', '红心', 'heart', 'love'],
  '😂': ['笑', '哭笑', '开心', 'face', 'joy', 'laugh', 'lol'],
  '😮': ['惊讶', '哇', 'wow', 'surprise'],
  '😢': ['哭', '伤心', 'sad', 'cry'],
  '🙏': ['祈祷', '谢谢', '拜托', 'pray', 'thanks', 'please'],
  '🔥': ['火', '赞', '热门', 'fire', 'lit'],
  '🎉': ['庆祝', '派对', 'party', 'celebrate'],
  '👏': ['鼓掌', 'clap', 'applause'],
  '🤔': ['思考', '想', 'think', 'hmm'],
  '😎': ['酷', '墨镜', 'cool', 'sunglasses'],
  '🥰': ['喜爱', '心动', 'love', 'adore'],
  '😅': ['尴尬', '汗', '笑', 'sweat', 'phew'],
  '😭': ['大哭', '伤心', 'sob', 'cry', 'loud'],
  '👀': ['眼睛', '看', 'eyes', 'look', 'watch'],
  '💪': ['力量', '肌肉', '加油', 'muscle', 'strong', 'flex'],
  '✅': ['对', '完成', 'check', 'done', 'yes'],
  '❌': ['错', '叉', 'cross', 'no', 'wrong'],
  '💯': ['满分', '一百', 'perfect', 'hundred'],
  '✨': ['闪亮', '星星', 'sparkle', 'shine'],
  '🙌': ['举手', '欢呼', 'raise', 'hooray'],
  '🤝': ['握手', '合作', 'handshake', 'deal'],
  '😘': ['亲', '飞吻', 'kiss'],
  '😴': ['睡', '困', 'sleep', 'zzz'],
  '😀': ['笑', '开心', 'grin', 'smile', 'happy'],
  '😃': ['笑', '开心', 'smile', 'happy'],
  '😄': ['笑', '开心', 'smile', 'happy'],
  '😁': ['笑', 'grin'],
  '😆': ['大笑', 'squint', 'laugh'],
  '🤣': ['笑倒', 'rofl', 'lol'],
  '🙂': ['微笑', 'slight', 'smile'],
  '😉': ['眨眼', 'wink'],
  '😊': ['害羞', '微笑', 'blush', 'smile'],
  '😇': ['天使', 'angel'],
  '😍': ['爱心眼', '爱', 'heart', 'love', 'eyes'],
  '🤩': ['花痴', '星星眼', 'star', 'struck'],
  '😋': ['好吃', '馋', 'yum', 'tasty'],
  '😛': ['吐舌', 'tongue'],
  '😜': ['调皮', '吐舌', 'wink', 'tongue'],
  '🤪': ['疯狂', 'crazy', 'zany'],
  '🤗': ['拥抱', 'hug'],
  '😐': ['无语', '面无表情', 'neutral'],
  '😑': ['无语', 'expressionless'],
  '😏': ['坏笑', '得意', 'smirk'],
  '😒': ['不屑', '无趣', 'unamused'],
  '🙄': ['翻白眼', 'roll', 'eyes'],
  '😬': ['尴尬', 'grimace'],
  '😯': ['惊讶', 'hushed'],
  '😪': ['困', 'sleepy'],
  '🤤': ['流口水', 'drool'],
  '😷': ['口罩', '生病', 'mask', 'sick'],
  '🤒': ['发烧', '生病', 'thermometer', 'sick'],
  '🤕': ['受伤', '绷带', 'bandage', 'hurt'],
  '🤢': ['恶心', '难受', 'nauseated', 'sick'],
  '🤮': ['吐', '恶心', 'vomit'],
  '🥵': ['热', '流汗', 'hot', 'heat'],
  '🥶': ['冷', '冻', 'cold', 'freeze'],
  '😵': ['晕', 'dizzy'],
  '🤯': ['爆炸', '震惊', 'mindblown', 'explode'],
  '🥳': ['派对', '庆祝', 'party', 'celebrate'],
  '🤓': ['书呆子', 'nerd'],
  '😕': ['困惑', 'confused'],
  '😟': ['担心', 'worried'],
  '🙁': ['不开心', '皱眉', 'frown'],
  '😲': ['吃惊', 'astonished'],
  '😳': ['脸红', '尴尬', 'flushed'],
  '🥺': ['恳求', '可怜', 'pleading'],
  '😨': ['害怕', 'fearful'],
  '😰': ['焦虑', '出汗', 'anxious', 'sweat'],
  '😥': ['失望', 'relieved', 'sad'],
  '😱': ['尖叫', '害怕', 'scream'],
  '😖': ['纠结', 'confounded'],
  '😣': ['坚持', 'persevere'],
  '😞': ['失望', 'disappointed'],
  '😩': ['疲惫', 'weary'],
  '😫': ['累', 'tired'],
  '😡': ['生气', '愤怒', 'angry', 'rage'],
  '😠': ['生气', 'angry'],
  '💀': ['骷髅', '死', 'skull', 'dead'],
  '💩': ['屎', 'poo', 'poop'],
  '🤡': ['小丑', 'clown'],
  // 手势
  '👋': ['挥手', '你好', 'bye', 'wave', 'hi'],
  '✋': ['停', '举手', 'stop', 'raise'],
  '🖖': ['瓦肯', '你好', 'vulcan', 'spock'],
  '👌': ['好的', 'OK', 'okay'],
  '✌️': ['胜利', '剪刀手', 'peace', 'victory'],
  '🤞': ['祈祷', '好运', 'fingers', 'crossed', 'luck'],
  '🤟': ['爱你', '摇滚', 'love'],
  '👈': ['左', 'point', 'left'],
  '👉': ['右', 'point', 'right'],
  '👆': ['上', '指', 'point', 'up'],
  '👇': ['下', '指', 'point', 'down'],
  '👎': ['差', '踩', 'thumbs', 'down', 'bad'],
  '✊': ['拳头', '加油', 'fist', 'fight'],
  '👊': ['拳头', '拳头打', 'punch', 'fist'],
  '🤛': ['左拳', 'fist', 'left'],
  '🤜': ['右拳', 'fist', 'right'],
  // 动物
  '🐶': ['狗', 'dog', 'puppy'],
  '🐱': ['猫', 'cat', 'kitty'],
  '🐭': ['老鼠', 'mouse'],
  '🐹': ['仓鼠', 'hamster'],
  '🐰': ['兔子', 'rabbit', 'bunny'],
  '🦊': ['狐狸', 'fox'],
  '🐻': ['熊', 'bear'],
  '🐼': ['熊猫', 'panda'],
  '🐨': ['考拉', '树袋熊', 'koala'],
  '🐯': ['老虎', 'tiger'],
  '🦁': ['狮子', 'lion'],
  '🐮': ['牛', 'cow'],
  '🐷': ['猪', 'pig'],
  '🐸': ['青蛙', 'frog'],
  '🐵': ['猴子', 'monkey'],
  '🐔': ['鸡', 'chicken'],
  '🐧': ['企鹅', 'penguin'],
  '🐦': ['鸟', 'bird'],
  '🦄': ['独角兽', 'unicorn'],
  '🐝': ['蜜蜂', 'bee'],
  '🦋': ['蝴蝶', 'butterfly'],
  '🐙': ['章鱼', 'octopus'],
  '🐟': ['鱼', 'fish'],
  '🐬': ['海豚', 'dolphin'],
  '🐳': ['鲸鱼', 'whale'],
  // 食物
  '🍎': ['苹果', 'apple'],
  '🍊': ['橘子', 'orange'],
  '🍌': ['香蕉', 'banana'],
  '🍉': ['西瓜', 'watermelon'],
  '🍇': ['葡萄', 'grape'],
  '🍓': ['草莓', 'strawberry'],
  '🍑': ['桃子', 'peach'],
  '🍔': ['汉堡', 'burger', 'hamburger'],
  '🍟': ['薯条', 'fries'],
  '🍕': ['披萨', 'pizza'],
  '🍜': ['面', '拉面', 'noodle', 'ramen'],
  '🍣': ['寿司', 'sushi'],
  '🍦': ['冰淇淋', 'icecream'],
  '🍩': ['甜甜圈', 'doughnut', 'donut'],
  '🍪': ['饼干', 'cookie'],
  '🎂': ['生日蛋糕', 'birthday', 'cake'],
  '🍫': ['巧克力', 'chocolate'],
  '☕️': ['咖啡', 'coffee'],
  '🍵': ['茶', 'tea'],
  '🍺': ['啤酒', 'beer'],
  // 活动
  '⚽️': ['足球', 'soccer', 'football'],
  '🏀': ['篮球', 'basketball'],
  '🏆': ['奖杯', '冠军', 'trophy', 'winner'],
  '🎵': ['音乐', '音符', 'music', 'note'],
  '🎶': ['音乐', '歌声', 'music', 'notes'],
  '🎤': ['麦克风', '唱歌', 'mic', 'karaoke'],
  '🎧': ['耳机', '音乐', 'headphone'],
  '🎸': ['吉他', 'guitar'],
  '🎹': ['钢琴', '键盘', 'piano'],
  '🎮': ['游戏手柄', '游戏', 'game', 'gaming'],
  // 物品
  '⌚️': ['手表', 'watch'],
  '📱': ['手机', 'phone', 'mobile'],
  '💻': ['电脑', '笔记本', 'laptop', 'computer'],
  '📷': ['相机', '拍照', 'camera', 'photo'],
  '💡': ['灯泡', '主意', '想法', 'idea', 'light', 'bulb'],
  '📖': ['书', '阅读', 'book', 'read'],
  '📚': ['书', '书堆', 'books'],
  '✏️': ['铅笔', '写字', 'pencil', 'write'],
  '📝': ['备忘录', '笔记', 'memo', 'note'],
  '💼': ['公文包', '工作', 'briefcase', 'work'],
  '🔑': ['钥匙', 'key'],
  '🔒': ['锁', 'lock'],
  '🔔': ['铃铛', '通知', 'bell', 'notification'],
  '🎁': ['礼物', '赠送', 'gift', 'present'],
  '🎈': ['气球', 'balloon'],
  '💎': ['钻石', '宝石', 'diamond', 'gem'],
  // 符号
  '🧡': ['橙心', 'orange', 'heart'],
  '💛': ['黄心', 'yellow', 'heart'],
  '💚': ['绿心', 'green', 'heart'],
  '💙': ['蓝心', 'blue', 'heart'],
  '💜': ['紫心', 'purple', 'heart'],
  '🖤': ['黑心', 'black', 'heart'],
  '💔': ['心碎', '分手', 'broken', 'heart'],
  '💕': ['双心', '爱', 'love', 'hearts'],
  '💞': ['旋转心', '爱', 'revolving', 'hearts'],
  '💓': ['跳动的心', '心跳', 'beating', 'heart'],
  '💗': ['变大的心', 'growing', 'heart'],
  '💖': ['闪亮心', 'sparkling', 'heart'],
  '💘': ['爱心箭', '心动', 'heart', 'arrow'],
  '⚡️': ['闪电', '电', 'lightning', 'bolt'],
  '⭐️': ['星', 'star'],
  '🌟': ['闪亮星', 'glowing', 'star'],
};
