// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

ConnectionStatus getConnectionStatus() =>
    RustLib.instance.api.crateApiMatrixGetConnectionStatus();

Future<void> initClient() => RustLib.instance.api.crateApiMatrixInitClient();

Future<List<ChatRoom>> getChatRooms() =>
    RustLib.instance.api.crateApiMatrixGetChatRooms();

Future<List<Space>> getSpaces() =>
    RustLib.instance.api.crateApiMatrixGetSpaces();

Future<List<ChatMessage>> getMessages({required String roomId}) =>
    RustLib.instance.api.crateApiMatrixGetMessages(roomId: roomId);

Future<List<Contact>> getContacts() =>
    RustLib.instance.api.crateApiMatrixGetContacts();

class ChatMessage {
  final String id;
  final String senderId;
  final String senderName;
  final String content;
  final String timestamp;
  final bool isMe;
  final MessageType msgType;
  final String? imageUrl;

  const ChatMessage({
    required this.id,
    required this.senderId,
    required this.senderName,
    required this.content,
    required this.timestamp,
    required this.isMe,
    required this.msgType,
    this.imageUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      content.hashCode ^
      timestamp.hashCode ^
      isMe.hashCode ^
      msgType.hashCode ^
      imageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          content == other.content &&
          timestamp == other.timestamp &&
          isMe == other.isMe &&
          msgType == other.msgType &&
          imageUrl == other.imageUrl;
}

class ChatRoom {
  final String id;
  final String name;
  final String? avatarUrl;
  final String lastMessage;
  final String lastMessageTime;
  final int unreadCount;
  final bool isPinned;
  final bool isMuted;

  const ChatRoom({
    required this.id,
    required this.name,
    this.avatarUrl,
    required this.lastMessage,
    required this.lastMessageTime,
    required this.unreadCount,
    required this.isPinned,
    required this.isMuted,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      avatarUrl.hashCode ^
      lastMessage.hashCode ^
      lastMessageTime.hashCode ^
      unreadCount.hashCode ^
      isPinned.hashCode ^
      isMuted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatRoom &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          lastMessage == other.lastMessage &&
          lastMessageTime == other.lastMessageTime &&
          unreadCount == other.unreadCount &&
          isPinned == other.isPinned &&
          isMuted == other.isMuted;
}

enum ConnectionStatus { connected, connecting, updating, disconnected }

class Contact {
  final String id;
  final String name;
  final String? avatarUrl;
  final String status;

  const Contact({
    required this.id,
    required this.name,
    this.avatarUrl,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ avatarUrl.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Contact &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl &&
          status == other.status;
}

enum MessageType { text, image }

class Space {
  final String id;
  final String name;
  final String? avatarUrl;

  const Space({required this.id, required this.name, this.avatarUrl});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Space &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatarUrl == other.avatarUrl;
}
